list: $/satriasp/paketbuilder/models/includes/columns.yaml
modelClass: Satriasp\PaketBuilder\Models\Includes
title: IncludeController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'satriasp/paketbuilder/includecontroller/update/:id'
