list: $/satriasp/paketbuilder/models/tujuan/columns.yaml
modelClass: Satriasp\PaketBuilder\Models\Tujuan
title: TujuanController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'satriasp/paketbuilder/tujuancontroller/update/:id'
